default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: qwerty
  host: localhost
  
development:
  <<: *default
  database: chat_development
 
test:
  <<: *default
  database: chat_test
 
production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  url: <%= ENV[''] %>
